name = input("Enter your name: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
Dream_Job = input("Enter your dream job: ")
Favorite_Sport = input("Enter your favorite sport: ")
print("Name:",name)
print("Age:",age)
print("City:",city)
print("Dream Job:",Dream_Job)
print("Favorite Sport:",Favorite_Sport)